// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC24s5q5hkzRUG0wbk50laSHRcvux54gGY',
    appId: '1:398470477323:web:c9eff7de5ff936eb42790e',
    messagingSenderId: '398470477323',
    projectId: 'new-project-o2enn5id',
    authDomain: 'new-project-o2enn5id.firebaseapp.com',
    storageBucket: 'new-project-o2enn5id.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyjF3iw3Mv_v0LcYvgNZ9UC6_F6H3GK3Y',
    appId: '1:398470477323:android:835930f9938045e642790e',
    messagingSenderId: '398470477323',
    projectId: 'new-project-o2enn5id',
    storageBucket: 'new-project-o2enn5id.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAK-763JuQqxkguleswtsSUjQtJ4Mizozo',
    appId: '1:398470477323:ios:e6cedaee2ca7d12642790e',
    messagingSenderId: '398470477323',
    projectId: 'new-project-o2enn5id',
    storageBucket: 'new-project-o2enn5id.appspot.com',
    iosClientId: '398470477323-sun6m8co1269gi7ge57c6r3vpoikhkqf.apps.googleusercontent.com',
    iosBundleId: 'com.example.testApp',
  );
}
